
export const LOGIN = "Login";
export const LOGIN_API_BEGIN   = 'LOGIN_API_BEGIN';
export const LOGIN_API_FAILURE = 'LOGIN_API_FAILURE';
export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const Types = {
    ADD_RESTORENT: 'ADD_RESTORENT',
    UPDATE_RESTORENT: 'UPDATE_RESTORENT',
    GET_RESTORENT_LIST: 'GET_RESTORENT_LIST',
    RESTORENT_API_ERROR: 'RESTORENT_API_ERROR',
    RESTORENT_API_LOADING: 'RESTORENT_API_LOADING',
  }